package com.example.ai

data class AiSkill(val id: String, val title: String, val prompt: String)

object AiSkillCatalog {
    val all: List<AiSkill> = listOf(
        AiSkill("001", "စာရေးဆရာ", "စာတစ်ပုဒ်ကို သေချာဖွဲ့စည်းပြီး ရေးပေးပါ"),
        AiSkill("002", "Email ရေးသားခြင်း", "Professional email တစ်စောင်ရေးပေးပါ"),
        AiSkill("003", "CV Builder", "အလုပ်လျှောက်ရန် CV တစ်စောင်ဖန်တီးပေးပါ"),
        AiSkill("004", "Cover Letter", "Cover letter တစ်စောင်ရေးပေးပါ"),
        AiSkill("005", "အင်တာဗျူးပြင်ဆင်", "Interview မေးခွန်းများနဲ့ အဖြေကောင်းများ ပြင်ဆင်ပေးပါ"),
        AiSkill("006", "Grammar Fix", "ဒီစာရဲ့ grammar ကို ပြင်ပေးပါ"),
        AiSkill("007", "စာလုံးပေါင်း", "စာလုံးပေါင်းနဲ့ ဝါကျအမှားတွေ စစ်ပေးပါ"),
        AiSkill("008", "Professional Rewrite", "ဒီစာကို professional ဖြစ်အောင် ပြန်ရေးပေးပါ"),
        AiSkill("009", "Shorten", "ဒီစာကို အဓိကအချက်မပျောက်ဘဲ တိုအောင်လုပ်ပေးပါ"),
        AiSkill("010", "Expand", "ဒီအကြောင်းအရာကို အသေးစိတ်ချဲ့ရေးပေးပါ"),
        AiSkill("011", "Summarize", "အောက်ပါအကြောင်းအရာကို အချက်လိုက် အကျဉ်းချုပ်ပေးပါ"),
        AiSkill("012", "Translate EN-MM", "အင်္ဂလိပ်မှ မြန်မာသို့ ဘာသာပြန်ပေးပါ"),
        AiSkill("013", "Translate MM-EN", "မြန်မာမှ အင်္ဂလိပ်သို့ သဘာဝကျကျ ဘာသာပြန်ပေးပါ"),
        AiSkill("014", "Translate Thai", "ဒီစာကို ထိုင်းဘာသာသို့ ဘာသာပြန်ပေးပါ"),
        AiSkill("015", "Translate Chinese", "ဒီစာကို တရုတ်ဘာသာသို့ ဘာသာပြန်ပေးပါ"),
        AiSkill("016", "Translate Japanese", "ဒီစာကို ဂျပန်ဘာသာသို့ ဘာသာပြန်ပေးပါ"),
        AiSkill("017", "Translate Korean", "ဒီစာကို ကိုရီးယားဘာသာသို့ ဘာသာပြန်ပေးပါ"),
        AiSkill("018", "Language Tutor", "ဘာသာစကားတစ်ခုကို အဆင့်လိုက် သင်ပေးပါ"),
        AiSkill("019", "Vocabulary", "နေ့စဉ်သုံး vocabulary 20 လုံးကို ဥပမာနဲ့ သင်ပေးပါ"),
        AiSkill("020", "Pronunciation Coach", "ဒီစကားလုံးတွေရဲ့ အသံထွက်ကို လေ့ကျင့်ပေးပါ"),
        AiSkill("021", "Study Plan", "စာလေ့လာရေးအစီအစဉ် ၇ ရက်စာ ပြုလုပ်ပေးပါ"),
        AiSkill("022", "Lesson Maker", "ဒီအကြောင်းအရာကို beginner lesson အဖြစ် သင်ခန်းစာလုပ်ပေးပါ"),
        AiSkill("023", "Quiz Maker", "ဒီအကြောင်းအရာကနေ quiz 10 ခု ထုတ်ပေးပါ"),
        AiSkill("024", "Flashcards", "မှတ်မိလွယ်အောင် flashcard မေးခွန်း/အဖြေ ဖန်တီးပေးပါ"),
        AiSkill("025", "Exam Prep", "စာမေးပွဲအတွက် အရေးကြီးဆုံးအချက်များ စုစည်းပေးပါ"),
        AiSkill("026", "Math Tutor", "ဒီသင်္ချာပုစ္ဆာကို အဆင့်လိုက်ရှင်းပြပေးပါ"),
        AiSkill("027", "Physics Tutor", "ဒီ Physics problem ကို formula နဲ့ ရှင်းပြပေးပါ"),
        AiSkill("028", "Chemistry Tutor", "ဒီ Chemistry အကြောင်းကို လွယ်လွယ်ရှင်းပြပေးပါ"),
        AiSkill("029", "Research Outline", "သုတေသနအကြောင်းအရာအတွက် outline တစ်ခုလုပ်ပေးပါ"),
        AiSkill("030", "Presentation", "Presentation slide အစီအစဉ်ဖန်တီးပေးပါ"),
        AiSkill("031", "Meeting Notes", "Meeting မှတ်တမ်းကို အချက်လိုက် စနစ်တကျ ပြန်စီပေးပါ"),
        AiSkill("032", "Action Items", "ဒီ meeting ထဲက လုပ်ဆောင်ရမယ့်အရာတွေ ထုတ်ပေးပါ"),
        AiSkill("033", "Project Planner", "Project တစ်ခုအတွက် task နဲ့ milestone အစီအစဉ်လုပ်ပေးပါ"),
        AiSkill("034", "Daily Planner", "ဒီနေ့အတွက် ဦးစားပေးအလိုက် အချိန်ဇယားလုပ်ပေးပါ"),
        AiSkill("035", "Weekly Planner", "တစ်ပတ်စာ အလုပ်အစီအစဉ်လုပ်ပေးပါ"),
        AiSkill("036", "Habit Builder", "အလေ့အကျင့်ကောင်းတစ်ခု တည်ဆောက်ဖို့ plan လုပ်ပေးပါ"),
        AiSkill("037", "Decision Helper", "ရွေးချယ်စရာနှစ်ခုကို အားသာချက်/အားနည်းချက်နဲ့ နှိုင်းယှဉ်ပေးပါ"),
        AiSkill("038", "Brainstorm", "ဒီခေါင်းစဉ်အတွက် idea 20 ခု စဉ်းစားပေးပါ"),
        AiSkill("039", "Business Idea", "အရင်းအနှီးနည်းနဲ့ စလုပ်နိုင်တဲ့ business idea များပေးပါ"),
        AiSkill("040", "Marketing Plan", "လုပ်ငန်းတစ်ခုအတွက် marketing plan တစ်ခုလုပ်ပေးပါ"),
        AiSkill("041", "Social Caption", "Facebook/Instagram အတွက် caption များရေးပေးပါ"),
        AiSkill("042", "Content Calendar", "Content calendar 30 ရက်စာ ပြုလုပ်ပေးပါ"),
        AiSkill("043", "SEO Keywords", "ဒီအကြောင်းအရာအတွက် SEO keyword ideas ထုတ်ပေးပါ"),
        AiSkill("044", "Product Description", "Product အတွက် ရောင်းအားကောင်းမယ့် description ရေးပေးပါ"),
        AiSkill("045", "Ad Copy", "ကြော်ငြာစာသား ၅ မျိုးရေးပေးပါ"),
        AiSkill("046", "Customer Reply", "Customer message ကို ယဉ်ကျေးပြီး professional ပြန်စာရေးပေးပါ"),
        AiSkill("047", "Sales Script", "အရောင်းပြောဆိုရန် script တစ်ခုရေးပေးပါ"),
        AiSkill("048", "Brand Naming", "Brand နာမည်အကြံပြုချက် 30 ခု ပေးပါ"),
        AiSkill("049", "Logo Brief", "Logo designer အတွက် design brief ရေးပေးပါ"),
        AiSkill("050", "Startup Pitch", "Startup pitch အတွက် အဓိကအချက်တွေ စုစည်းပေးပါ"),
        AiSkill("051", "Budget Plan", "လစဉ် budget အစီအစဉ်တစ်ခု ပြုလုပ်ပေးပါ"),
        AiSkill("052", "Expense Categorizer", "အသုံးစရိတ်တွေကို category ခွဲပြီး စုစည်းပေးပါ"),
        AiSkill("053", "Savings Plan", "ငွေစုဖို့ လက်တွေ့ကျတဲ့ plan တစ်ခုလုပ်ပေးပါ"),
        AiSkill("054", "Spreadsheet Formula", "Spreadsheet အတွက် လိုအပ်တဲ့ formula ကို ရေးပေးပါ"),
        AiSkill("055", "Data Cleanup", "ဒီ data ကို သန့်ရှင်းပြီး စနစ်တကျ ပြန်စီပေးပါ"),
        AiSkill("056", "Data Insights", "ပေးထားတဲ့ data ထဲက အရေးကြီးတဲ့ trend တွေရှာပေးပါ"),
        AiSkill("057", "SQL Helper", "ဒီလို data ရဖို့ SQL query ရေးပေးပါ"),
        AiSkill("058", "JSON Helper", "JSON structure ကို စစ်ပြီး မှန်ကန်အောင် ပြင်ပေးပါ"),
        AiSkill("059", "Regex Builder", "ဒီလိုစာသားကိုရှာဖို့ regex ရေးပေးပါ"),
        AiSkill("060", "API Design", "REST API endpoint design တစ်ခု အကြံပြုပါ"),
        AiSkill("061", "Kotlin Developer", "ဒီ feature ကို Kotlin နဲ့ရေးပေးပါ"),
        AiSkill("062", "Android Developer", "Android app feature တစ်ခုကို implementation plan နဲ့ရေးပေးပါ"),
        AiSkill("063", "Compose UI", "Jetpack Compose UI code ရေးပေးပါ"),
        AiSkill("064", "Python Developer", "ဒီအလုပ်အတွက် Python script ရေးပေးပါ"),
        AiSkill("065", "JavaScript Developer", "ဒီ feature ကို JavaScript နဲ့ရေးပေးပါ"),
        AiSkill("066", "HTML/CSS", "Responsive HTML/CSS page တစ်ခုရေးပေးပါ"),
        AiSkill("067", "Bug Finder", "ဒီ code ထဲက bug တွေရှာပြီး ပြင်ပေးပါ"),
        AiSkill("068", "Code Review", "ဒီ code ကို security/performance/readability အရ review လုပ်ပေးပါ"),
        AiSkill("069", "Refactor", "ဒီ code ကို ပိုရှင်းပြီး maintainable ဖြစ်အောင် refactor လုပ်ပေးပါ"),
        AiSkill("070", "Test Generator", "ဒီ function အတွက် unit tests ရေးပေးပါ"),
        AiSkill("071", "Git Helper", "Git command တွေကို အဆင့်လိုက်ပေးပါ"),
        AiSkill("072", "GitHub README", "Project အတွက် README ကောင်းကောင်းရေးပေးပါ"),
        AiSkill("073", "Architecture", "ဒီ project အတွက် scalable architecture အကြံပြုပါ"),
        AiSkill("074", "Performance", "App performance တိုးတက်အောင် လုပ်ရမယ့်အချက်တွေ ပေးပါ"),
        AiSkill("075", "Security Review", "ဒီ design/code ရဲ့ security risks တွေရှာပေးပါ"),
        AiSkill("076", "Privacy Checklist", "App privacy အတွက် checklist တစ်ခုလုပ်ပေးပါ"),
        AiSkill("077", "Debug Assistant", "Error log ကိုဖတ်ပြီး root cause နဲ့ fix ကိုပြောပေးပါ"),
        AiSkill("078", "Release Checklist", "Android release မလုပ်ခင် စစ်ဆေးရမယ့် checklist ပေးပါ"),
        AiSkill("079", "Recipe Planner", "အိမ်မှာရှိတဲ့ပစ္စည်းတွေနဲ့ ချက်ပြုတ်နိုင်တဲ့ဟင်းလျာအကြံပြုပါ"),
        AiSkill("080", "Meal Planner", "တစ်ပတ်စာ အစားအစာအစီအစဉ်လုပ်ပေးပါ"),
        AiSkill("081", "Grocery List", "Meal plan ကနေ shopping list ထုတ်ပေးပါ"),
        AiSkill("082", "Travel Planner", "ခရီးစဉ်တစ်ခုအတွက် itinerary အစီအစဉ်လုပ်ပေးပါ"),
        AiSkill("083", "Packing List", "ခရီးသွားရန် လိုအပ်တဲ့ packing list လုပ်ပေးပါ"),
        AiSkill("084", "Workout Planner", "လေ့ကျင့်ခန်းအစီအစဉ်တစ်ခု စီစဉ်ပေးပါ"),
        AiSkill("085", "Fitness Habit", "နေ့စဉ် fitness habit တည်ဆောက်ဖို့ plan လုပ်ပေးပါ"),
        AiSkill("086", "Mind Map", "ဒီအကြောင်းအရာကို mind map ပုံစံနဲ့ စီပေးပါ"),
        AiSkill("087", "Checklist", "ဒီအလုပ်အတွက် checklist တစ်ခု ဖန်တီးပေးပါ"),
        AiSkill("088", "SOP Maker", "အလုပ်တစ်ခုအတွက် SOP အဆင့်လိုက်ရေးပေးပါ"),
        AiSkill("089", "How-To", "ဒီအလုပ်ကို beginner အတွက် step-by-step သင်ပေးပါ"),
        AiSkill("090", "Explain Simple", "ဒီအကြောင်းအရာကို ကလေးတစ်ယောက်နားလည်အောင် ရှင်းပြပါ"),
        AiSkill("091", "Compare", "ဒီရွေးချယ်စရာတွေကို ဇယားနဲ့ နှိုင်းယှဉ်ပေးပါ"),
        AiSkill("092", "Pros Cons", "ဒီဆုံးဖြတ်ချက်ရဲ့ pros/cons ကို ရှင်းပြပေးပါ"),
        AiSkill("093", "FAQ Maker", "ဒီ product/service အတွက် FAQ 20 ခုရေးပေးပါ"),
        AiSkill("094", "Support Agent", "Customer support agent တစ်ယောက်လို ပြန်ဖြေပေးပါ"),
        AiSkill("095", "Idea Critic", "ဒီ idea ရဲ့ အားနည်းချက်နဲ့ တိုးတက်နိုင်မယ့်အချက်တွေ ဝေဖန်ပေးပါ"),
        AiSkill("096", "Creative Story", "ဒီ theme နဲ့ စိတ်ဝင်စားစရာ ဇာတ်လမ်းတိုရေးပေးပါ"),
        AiSkill("097", "Poem", "ဒီအကြောင်းအရာကို ကဗျာပုံစံရေးပေးပါ"),
        AiSkill("098", "Script Writer", "Video အတွက် script တစ်ခုရေးပေးပါ"),
        AiSkill("099", "YouTube Outline", "YouTube video အတွက် hook + outline + CTA ပြုလုပ်ပေးပါ"),
        AiSkill("100", "Podcast", "Podcast episode အတွက် outline လုပ်ပေးပါ"),
        AiSkill("101", "Interview Questions", "ဒီအလုပ်ရာထူးအတွက် interview questions 20 ခု ထုတ်ပေးပါ"),
        AiSkill("102", "Role Play", "ဒီအခြေအနေကို role-play လုပ်ပြီး လေ့ကျင့်ပေးပါ"),
        AiSkill("103", "Negotiation", "ညှိနှိုင်းဆွေးနွေးရာမှာ အသုံးချနိုင်တဲ့ strategy ပေးပါ"),
        AiSkill("104", "Conflict Resolution", "အငြင်းပွားမှုတစ်ခုကို ငြိမ်းချမ်းစွာ ဖြေရှင်းဖို့ အကြံပေးပါ"),
        AiSkill("105", "Time Management", "အချိန်စီမံခန့်ခွဲမှုအတွက် လက်တွေ့ကျတဲ့နည်းလမ်းပေးပါ"),
        AiSkill("106", "Focus Coach", "အာရုံစူးစိုက်နိုင်ဖို့ 25-minute focus session တစ်ခု စီစဉ်ပေးပါ"),
        AiSkill("107", "Note Organizer", "ဒီမှတ်စုတွေကို ခေါင်းစဉ်နဲ့ category အလိုက် စီပေးပါ"),
        AiSkill("108", "Knowledge Extractor", "ဒီစာထဲက facts, names, dates, tasks တွေထုတ်ပေးပါ"),
        AiSkill("109", "Action Summary", "ဒီအကြောင်းအရာကနေ လက်တွေ့လုပ်ရမယ့်အချက် 5 ခုထုတ်ပေးပါ"),
        AiSkill("110", "Question Generator", "ဒီအကြောင်းအရာကို နားလည်ဖို့ မေးသင့်တဲ့မေးခွန်းတွေ ထုတ်ပေးပါ"),
        AiSkill("111", "Prompt Engineer", "AI အတွက် ဒီ request ကို prompt ကောင်းတစ်ခုအဖြစ် ပြန်ရေးပေးပါ"),
        AiSkill("112", "AI Workflow", "ဒီအလုပ်ကို AI နဲ့ အဆင့်လိုက် automate လုပ်နိုင်မယ့် workflow တစ်ခုလုပ်ပေးပါ"),
        AiSkill("113", "Personal Assistant", "ဒီနေ့အလုပ်တွေကို ဦးစားပေးပြီး အကူအညီပေးပါ"),
        AiSkill("114", "Daily Review", "ဒီနေ့လုပ်ခဲ့တာတွေကို review လုပ်ဖို့ template ပေးပါ"),
        AiSkill("115", "Goal Planner", "ရည်မှန်းချက်တစ်ခုအတွက် 30/60/90 day plan လုပ်ပေးပါ"),
        AiSkill("116", "Habit Tracker", "Habit tracker အတွက် ရိုးရှင်းတဲ့ဇယားဖန်တီးပေးပါ"),
        AiSkill("117", "Document Outline", "Document တစ်ခုရေးဖို့ professional outline လုပ်ပေးပါ"),
        AiSkill("118", "Report Writer", "ပေးထားတဲ့အချက်အလက်နဲ့ report တစ်စောင်ရေးပေးပါ"),
        AiSkill("119", "Executive Summary", "ရှည်လျားတဲ့အကြောင်းအရာကို executive summary အဖြစ်ရေးပေးပါ"),
        AiSkill("120", "Risk Matrix", "Project risk တွေကို probability/impact အလိုက် ခွဲပေးပါ"),
        AiSkill("121", "SWOT", "ဒီလုပ်ငန်း/idea အတွက် SWOT analysis လုပ်ပေးပါ"),
        AiSkill("122", "KPI Builder", "လုပ်ငန်းတစ်ခုအတွက် တိုင်းတာနိုင်တဲ့ KPI များသတ်မှတ်ပေးပါ"),
        AiSkill("123", "Roadmap", "Product/project roadmap တစ်ခု ဖန်တီးပေးပါ"),
        AiSkill("124", "Feature Spec", "App feature တစ်ခုအတွက် product specification ရေးပေးပါ"),
        AiSkill("125", "User Stories", "Feature အတွက် user stories နဲ့ acceptance criteria ရေးပေးပါ"),
        AiSkill("126", "QA Checklist", "Feature အတွက် QA test checklist လုပ်ပေးပါ"),
        AiSkill("127", "Accessibility", "UI accessibility တိုးတက်အောင် စစ်ဆေးပေးပါ"),
        AiSkill("128", "Localization", "App စာသားတွေကို localization-ready ဖြစ်အောင် ပြင်ပေးပါ"),
        AiSkill("129", "Final Polish", "ဒီစာ/အကြောင်းအရာကို final polished version အဖြစ် ပြန်ရေးပေးပါ"),
    )

    val count: Int get() = all.size
}
